version: '3'
services:
  backend-service:
    image: backend
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - redis_connection_string=redis://redis-server:6379
    networks:
      - redis-application-network
  redis-server:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-application-network
networks:
  redis-application-network:
    driver: bridge